title: "Правила поведения в сообществах"
description: ""

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "metacraft"
  twitter: "metadatafdn"
